# Generated by Django 5.0.2 on 2024-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_ad_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advetiser',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advetiser',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
