# Generated by Django 5.0.2 on 2024-02-23 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_ad_clicks_ad_views_advetiser_clicks_advetiser_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advetiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advetiser',
            name='views',
        ),
        migrations.AddField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('user_ip', models.CharField(max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('user_ip', models.CharField(max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertiser_management.ad')),
            ],
        ),
    ]
