# Generated by Django 5.0.2 on 2024-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_remove_ad_clicks_remove_ad_views_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='views',
            new_name='click',
        ),
        migrations.RenameModel(
            old_name='clicks',
            new_name='view',
        ),
    ]
