# Generated by Django 5.0.2 on 2024-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_rename_views_click_rename_clicks_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='advetiser',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advetiser',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
