# Generated by Django 5.0.2 on 2024-02-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_advetiser_clicks_advetiser_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advetiser'),
        ),
        migrations.AlterField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='click',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='view',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
