# Generated by Django 5.0.2 on 2024-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0007_alter_ad_advertiser_alter_click_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='user_ip',
            field=models.CharField(max_length=45),
        ),
    ]
