# Generated by Django 5.0.2 on 2024-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0009_alter_click_created_on_alter_view_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
