CREATE TABLE ADVERTISERS(
   ID          		INT NOT NULL,
   NAME        		VARCHAR (100) NOT NULL,
   CLICKS_COUNT     INT,
   VIEWS_COUNT      INT,
   PRIMARY KEY (ID)
);
CREATE TABLE ADS(
   ID          		INT NOT NULL,
   TITLE        	VARCHAR (100) NOT NULL,
   IMG_URL        	VARCHAR (100) NOT NULL,
   LINK	        	VARCHAR (100) NOT NULL,
   CLICKS_COUNT     INT,
   VIEWS_COUNT      INT,
   ADVERTISER_ID	INT,
   CONSTRAINT FK_ADVERTISER 
   FOREIGN KEY(ADVERTISER_ID) 
   REFERENCES ADVERTISERS(ID),
   PRIMARY KEY (ID)
);

INSERT INTO ADVERTISERS (ID, NAME, CLICKS_COUNT, VIEWS_COUNT)
VALUES (1, 'advertiser1', 10, 5),(2, 'advertiser2', 14, 9);

INSERT INTO ADS (ADVERTISER_ID, ID, TITLE, IMG_URL, LINK, CLICKS_COUNT, VIEWS_COUNT)
VALUES (1, 1, 'title1', 'url1', 'link1', 11, 8),(2, 2, 'title2', 'url2', 'link2', 14, 20);